[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
dist-name = "python-project-structure"
module = "pythonprojectstructure"
author = "Ross Patterson"
author-email = "me@rpatterson.net"
home-page = "https://github.com/rpatterson/python-project-structure"
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.7"
description-file = "README.rst"
[tool.flit.metadata.requires-extra]
dev = [
    "pre-commit",
    "coverage",
]

[tool.coverage.run]
branch = true
source = ["src"]
[tool.coverage.report]
fail_under = 100
show_missing = true
