[tool.poetry]
name = "python-project-structure"
version = "0.1.0"
description = "Python project structure foundation or template"
authors = ["Ross Patterson <me@rpatterson.net>"]

[tool.poetry.dependencies]
python = "^3.7"
coverage = {extras = ["toml"], version = "^5.0.4"}

[tool.poetry.dev-dependencies]
pre-commit = "^2.2.0"
coverage = "^5.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.coverage.run]
branch = true
source = ["src"]
[tool.coverage.report]
fail_under = 100
show_missing = true
