[tool.poetry]
name = "python-project-structure"
version = "0.1.0"
description = "Python project structure foundation or template"
authors = ["Ross Patterson <me@rpatterson.net>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pre-commit = "^2.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
