name: Run linter, tests and, and release

on: [push]

jobs:

  ci-cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:

      - uses: actions/checkout@master

      - name: Add user installs to PATH
        run: |
          echo "::add-path::$HOME/.local/bin"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python bootstrapping dependencies
        uses: actions/cache@master
        env:
          cache-name: cache-pip-installs
        with:
          path: ~/.local
          # Never get a cache hit to force always caching the upgraded dependencies
          key: ${{ github.ref == 'refs/heads/master' }}-${{ runner.os }}-test-${{ env.cache-name }}-${{ github.sha }}
          # Always re-use the cache and then upgrade
          restore-keys:
            ${{ github.ref == 'refs/heads/master' }}-${{ runner.os }}-test-${{ env.cache-name }}-

      - name: Install dependencies
        run: |
          python -m pip install -U --upgrade-strategy=eager --user pip
          pip install -U --upgrade-strategy=eager --user tox tox-gh-actions

      - name: Cache tox virtual environments
        uses: actions/cache@master
        env:
          cache-name: cache-tox-envs
        with:
          path: ./.tox
          # Never get a cache hit to force always caching the upgraded dependencies
          key: ${{ github.ref == 'refs/heads/master' }}-${{ runner.os }}-test-${{ env.cache-name }}-${{ github.sha }}
          # Always re-use the cache and then upgrade
          restore-keys:
            ${{ github.ref == 'refs/heads/master' }}-${{ runner.os }}-test-${{ env.cache-name }}-

      - name: Test with tox
        run: |
          make upgrade
          tox

      - name: Bump version and push tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build a binary wheel and a source tarball
        run: |
          .tox/py3/bin/python setup.py sdist bdist_wheel

      - name: Publish distribution to Test PyPI for devel branches
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution to PyPI for master
        if: github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
