name: Run tests and linter and release on master

on: [push]

jobs:


  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:

    - uses: actions/checkout

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python bootstrapping dependencies
      uses: actions/cache
      env:
        cache-name: cache-pip-installs
      with:
        path: ~/.local
        key: ${{ runner.os }}-test-${{ env.cache-name }}

    - name: Install dependencies
      run: |
        python -m pip install -U --upgrade-strategy=eager --user pip
        pip install -U --upgrade-strategy=eager --user tox tox-gh-actions

    - name: Cache tox virtual environments
      uses: actions/cache
      env:
        cache-name: cache-tox-envs
      with:
        path: ./.tox
        key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('./setup.*') }}-${{ hashFiles('./tox.ini') }}

    - name: Test with tox
      run: tox


  release:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Bump version and push tag
        id: github-tag-action
        uses: mathieudutour/github-tag-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
